### ISSUE TITLE
Bug: Fix Inconsistent Report Generation

### ISSUE THREAD

**Issue by AArchange** [liberu-accounting/accounting-laravel#127]
Description: Resolve the issue where financial reports are occasionally generated with inconsistent data or formatting errors. Ensure all generated reports accurately reflect the current financial status.
Tasks:
Identify and correct inconsistencies in the report generation process.
Validate data sources and ensure accurate data retrieval.
Standardize report formatting to maintain consistency.
Acceptance Criteria:
Reports are generated with consistent and accurate data.
Formatting is standardized across all reports.
No errors occur during the report generation process.

**Comment by fosterushka** [comment]
> ### Details
> No one will work with you anymore No one will work with you anymore No one will work with you anymore No one will work with you anymore No one will work with you anymore No one will work with you anymore No one will work with you anymore No one will work with you anymore No one will work with you anymore No one will work with you anymore No one will work with you anymore No one will work with you anymore No one will work with you anymore

Hey mate i was trying to help this open source projects and improve them, but i notice so many issues with a scam alert, could you please share some details what's going on ? please email me man1080@yandex.com
