### ISSUE TITLE
no home layout

### ISSUE THREAD

**Issue by rickysut** [liberu-accounting/accounting-laravel#128]
### Details
@extends('layouts.home') not found anywhere

**Comment by curtisdelicata** [comment]
We are aware, under active development.

**Comment by curtisdelicata** [comment]
Fixed.

**Comment by rickysut** [comment]
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/1cbce6ec-106b-4b03-ae39-d77eabd5cde8">
i got undefined variable $slot, why?
