### ISSUE TITLE
Test not working

### ISSUE THREAD

**Issue by eskayamadeus** [liberu-accounting/accounting-laravel#135]
This is  a **bug**.

### Prerequisites
* [ x ] Are you running the latest version?
* [ x ] Are you reporting to the correct repository?
* [ x ] Did you check the documentation?
* [ - ] Did you perform a cursory search?

### Description
I get a PHP fatal error when running the tests.

### Steps to Reproduce
1. Run `./vendor/bin/phpunit` or `php artisan test`

### Expected behavior
All tests should pass without issues.

### Actual behavior
Error was reported. `PHP Fatal error:  Cannot declare class App\Filament\Admin\Resources\AccountResource, because the name is already in use in /home/eskay/projects/accounting-laravel/app/Filament/App/Resources/AccountResource.php on line 21`

![image](https://github.com/user-attachments/assets/ceb8e645-8088-49d8-8118-e929c2b44cfb)

**Comment by curtisdelicata** [comment]
We are aware, under active development.
