### ISSUE TITLE
Sweep: Route not found on first run

### ISSUE THREAD

**Issue by marvoh** [liberu-accounting/accounting-laravel#39]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

On setting up the application and running, /admin returns the error 

`Route` [login] not defined.`

I am new to Laravel so the best I could do was look around the net and stumbled across something similar in the Filament issues page [here](https://github.com/filamentphp/filament/discussions/5226) but the proposed solution did not work.

Would you know how to get this to run?

### Steps to Reproduce

1. Build docker container
2. Check application in browser

### Expected behavior

Expecting a login page to be presented
### Actual behavior
Route [login] not defined. is the error given

**Comment by curtisdelicata** [comment]
This will be fixed. If you fix it before we do, please open a pull request.

**Comment by curtisdelicata** [comment]
Actually try /admin

**Comment by marvoh** [comment]
I tried /admin and experienced the same issue.

I can try re-install and test again if it works on your end.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by curtisdelicata** [comment]
Does this still happen when using /admin/login

Soon we will be using Jetstream for auth ans and teams tenancy so that will definitely solve if not already.

**Comment by curtisdelicata** [comment]
@marvoh
